-- 조건에 맞는 도서와 저자 리스트 출력하기
SELECT b.BOOK_ID, 
       a.AUTHOR_NAME, 
       DATE_FORMAT(b.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK b
LEFT JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE b.CATEGORY LIKE '경제'
ORDER BY PUBLISHED_DATE